fix lint?

diff --git a/.github/workflows/circle_trigger.yml b/.github/workflows/circle_trigger.yml
--- a/.github/workflows/circle_trigger.yml
+++ b/.github/workflows/circle_trigger.yml
@@ -47,26 +47,26 @@ jobs:
           fi
 
       - name: Trigger CircleCI Pipeline
-          env:
-            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
-            MAKE_TARGET: ${{ steps.determine-target.outputs.target }}
-          run: |
-            # Validate branch name isn't empty
-            if [ -z "$BRANCH_NAME" ]; then
-              echo "::error::Branch name is empty"
-              exit 1
-            fi
-        
-            curl -X POST \
-              -H "Content-Type: application/json" \
-              -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
-              -d '{
-                "branch": "'"$BRANCH_NAME"'",
-                "parameters": {
-                  "make_target": "'"$MAKE_TARGET"'"
-                }
-              }' \
-              "https://circleci.com/api/v2/project/gh/psobolewskiPhD/napari-docs/pipeline"
+        env:
+          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+          MAKE_TARGET: ${{ steps.determine-target.outputs.target }}
+        run: |
+          # Validate branch name isn't empty
+          if [ -z "$BRANCH_NAME" ]; then
+            echo "::error::Branch name is empty"
+            exit 1
+          fi
+    
+          curl -X POST \
+            -H "Content-Type: application/json" \
+            -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
+            -d '{
+              "branch": "'"$BRANCH_NAME"'",
+              "parameters": {
+                "make_target": "'"$MAKE_TARGET"'"
+              }
+            }' \
+            "https://circleci.com/api/v2/project/gh/psobolewskiPhD/napari-docs/pipeline"
         
       - name: Wait for CircleCI Job Completion
         uses: larsoner/circleci-artifacts-redirector-action@master
